name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Test parser
        run: npm run test-parser

      - name: Install node dependencies
        run: npm install

      - name: Test frontend
        run: npm run test-frontend
